export enum EPageType {
  BuyLanding = "buy-landing-page",
  SoldLanding = "sold-landing-page",
  RentLanding = "rent-landing-page",
  SoldSearchResult = "sold-search-result-page",
  RentSearchResult = "rent-search-result-page",
  BuySearchResult = "buy-search-result-page",
  SoldPropertyDetail = "sold-property-details",
  RentPropertyDetail = "rent-property-details",
  BuyPropertyDetail = "buy-property-details",
  ProfileLandingPage = "profile-landing-page",
  StateProfile = "state-profile-page",
  CityProfile = "city-profile-page",
  RegionProfile = "region-profile-page",
  SuburbProfile = "suburb-profile-page",
  FindAgentLanding = "find-agent-landing-page",
  AgentDetail = "agent-detail-page",
  AgencySearchResult = "agency-search-result-page",
  AgencyDetail = "agency-detail-page",
  AuctionLanding = "auction-landing-page",
  AuctionSearchResult = "auction-search-result-page",
  PriceEstimatorLanding = "price-estimator-landing-page",
  PriceEstimatorSearchResult = "price-estimator-result-page",
}
